desc: <app>
triggers:
- name: ""
  pattens:
  - '**/*.*'
  env:
    DEBUG: "1"
  cmd: cd /go/src/github.com/andreiavrammsd/go-live-reload/apps/<app> && go get -t && go vet -composites=false && go build -o /bin/<app> && /bin/<app>
  shell: true
  delay: 100ms
  stop_timeout: 500ms
  signal: KILL
  kill_signal: ""
watch_paths:
- /go/src/github.com/andreiavrammsd/go-live-reload/apps/<app>
- /go/src/github.com/andreiavrammsd/go-live-reload/packages
watch_depth: 1
